version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    restart: always
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    
  frontend:
    container_name: foodgram-front
    image: vovalee/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
      - static:/app/result_build/build/static
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: vovalee/foodgram_nginx
    ports:
      - "8080:80"
    volumes:
      - static:/static/
      - media:/media
    depends_on:
      - backend
      - frontend

  
  backend:
    container_name: foodgram-backend
    env_file: ../.env
    image: vovalee/foodgram_backend
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

